In [2]:
import tensorflow as tf

C:\Users\yangwa\AppData\Local\Continuum\miniconda2\envs\py36\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)


In [3]:
def approx_ranks(logits, alpha=10.):
    list_size = tf.shape(input=logits)[1]
    x = tf.tile(tf.expand_dims(logits, 2), [1, 1, list_size])
    y = tf.tile(tf.expand_dims(logits, 1), [1, list_size, 1])
    pairs = tf.sigmoid(alpha * (y - x))
    return tf.reduce_sum(input_tensor=pairs, axis=-1) + .5

In [4]:
def get_ranks(scores):
    x = tf.expand_dims(scores, 2)
    y = tf.expand_dims(scores, 1)
    #pairs = tf.nn.relu(tf.sign(y-x))
    pairs = tf.sign(y-x) + 1
    return (tf.reduce_sum(input_tensor=pairs, axis=-1) + 1)/2

In [5]:
logits = tf.placeholder(shape=[1, 10], dtype=tf.float32)
aranks = approx_ranks(logits)

In [6]:
ranks = get_ranks(logits)

In [7]:
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config = config)

In [9]:
sess.run(ranks, feed_dict={
    logits: [[3,6,2,5,10,9,7,4,8,1]]
})

array([[  8.,   5.,   9.,   6.,   1.,   2.,   4.,   7.,   3.,  10.]], dtype=float32)

In [10]:
sess.run(ranks, feed_dict={
    logits: [[4,7,2,3,1,1,0,9,6,0]]
})

array([[ 4. ,  2. ,  6. ,  5. ,  7.5,  7.5,  9.5,  1. ,  3. ,  9.5]], dtype=float32)

In [ ]:
sess.run(ranks, feed_dict={
    logits: [[]]
})

In [13]:
sess.run(aranks, feed_dict={
    logits: [[1,2,3,4,5,6,7,8,9,10]]
})

array([[ 9.99995422,  9.        ,  8.        ,  7.        ,  6.        ,
         5.        ,  4.        ,  3.        ,  2.        ,  1.00004542]], dtype=float32)